paths:
  /services:
    get:
      tags:
        - Services
      description: Get all services
      parameters:
        - name: _start
          in: query
          schema:
            type: integer
          description: The number of the first record for pagination
        - name: _end
          in: query
          schema:
            type: integer
          description: The number of the last record for pagination
        - name: _sort
          in: query
          schema:
            type: string
          description: The name of the field to sort by
        - name: _order
          in: query
          schema:
            type: string
            enum:
              - ASC
              - DESC
          description: The sorting order
        - name: id
          in: query
          schema:
            type: integer
          description: The ids of the records to query
        - name: companyId
          in: query
          schema:
            type: integer
          description: The id of the services' owner
        - name: formatId
          in: query
          schema:
            type: integer
          description: The id of the services' format
        - name: themeId
          in: query
          schema:
            type: integer
          description: The id of the services' theme
        - name: userId
          in: query
          schema:
            type: integer
          description: The id of the services' visitor
        - name: upcoming
          in: query
          schema:
            type: boolean
          description: Are services upcoming or not (the parameter is compared with publishDate)
        - name: notPublished
          in: query
          schema:
            type: boolean
          description: Are services not published or not (the parameter is compared with publishDate)
        - name: dateFrom
          in: query
          schema:
            type: string
          description: The earliest date (the parameter is compared with date)
        - name: dateTo
          in: query
          schema:
            type: string
          description: The latest date (the parameter is compared with date)
        - name: q
          in: query
          schema:
            type: string
          description: The string for general search by name
      responses:
        200:
          description: All services found
          headers:
            X-Total-Count:
              schema:
                type: integer
              description: Total count of the records
          content:
            application/json; charset=utf-8:
              schema:
                $ref: '#definitions/services'
        400:
          description: The format of the data is invalid
          content:
            application/json; charset=utf-8:
              schema:
                $ref: '#definitions/error'
    post:
      tags:
        - services
      security:
        - bearerAuth: []
      description: Create an service
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#definitions/service_create'
      responses:
        201:
          description: service was created
          content:
            application/json; charset=utf-8:
              schema:
                $ref: '#definitions/service'
        400:
          description: The format of the data is invalid
          content:
            application/json; charset=utf-8:
              schema:
                $ref: '#definitions/error'
        401:
          description: Bearer token is invalid
          content:
            application/json; charset=utf-8:
              schema:
                $ref: '#definitions/error'
        404:
          description: The company was not found by id
          content:
            application/json; charset=utf-8:
              schema:
                $ref: '#definitions/error'
  /services/{id}:
    parameters:
      - name: id
        in: path
        schema:
          type: integer
        required: true
        description: The id of the record to query
    get:
      tags:
        - services
      description: Get the service by id
      responses:
        200:
          description: Found the service by id
          content:
            application/json; charset=utf-8:
              schema:
                $ref: '#definitions/service'
        404:
          description: The service was not found by id
          content:
            application/json; charset=utf-8:
              schema:
                $ref: '#definitions/error'
    put:
      tags:
        - services
      security:
        - bearerAuth: []
      description: Update the service by id
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#definitions/service_update'
      responses:
        201:
          description: Service was updated
          content:
            application/json; charset=utf-8:
              schema:
                $ref: '#definitions/service'
        400:
          description: The format of the data is invalid
          content:
            application/json; charset=utf-8:
              schema:
                $ref: '#definitions/error'
        401:
          description: Bearer token is invalid
          content:
            application/json; charset=utf-8:
              schema:
                $ref: '#definitions/error'
        403:
          description: You do not have proper rights
          content:
            application/json; charset=utf-8:
              schema:
                $ref: '#definitions/error'
        404:
          description: The service was not found by id
          content:
            application/json; charset=utf-8:
              schema:
                $ref: '#definitions/error'
    delete:
      tags:
        - services
      security:
        - bearerAuth: []
      description: Remove the service by id
      responses:
        200:
          description: service was removed
          content:
            application/json; charset=utf-8:
              schema:
                $ref: '#definitions/service'
        401:
          description: Bearer token is invalid
          content:
            application/json; charset=utf-8:
              schema:
                $ref: '#definitions/error'
        403:
          description: You do not have proper rights
          content:
            application/json; charset=utf-8:
              schema:
                $ref: '#definitions/error'
        404:
          description: The service was not found by id
          content:
            application/json; charset=utf-8:
              schema:
                $ref: '#definitions/error'
  /services/{id}/poster:
    parameters:
      - name: id
        in: path
        schema:
          type: integer
        required: true
        description: The id of the record to query
    put:
      tags:
        - services
      security:
        - bearerAuth: []
      description: Update the service's poster by id
      parameters:
        - in: formData
          name: poster
          type: file
          required: true
          description: The file to upload.
      responses:
        201:
          description: The service's poster was updated
          content:
            application/json; charset=utf-8:
              schema:
                $ref: '#definitions/service'
        400:
          description: The format of the file is invalid
          content:
            application/json; charset=utf-8:
              schema:
                $ref: '#definitions/error'
        401:
          description: Bearer token is invalid
          content:
            application/json; charset=utf-8:
              schema:
                $ref: '#definitions/error'
        403:
          description: You do not have proper rights
          content:
            application/json; charset=utf-8:
              schema:
                $ref: '#definitions/error'
        404:
          description: The service was not found by id
          content:
            application/json; charset=utf-8:
              schema:
                $ref: '#definitions/error'
    delete:
      tags:
        - services
      security:
        - bearerAuth: []
      description: Remove the service's poster by id
      responses:
        200:
          description: The service's poster was removed
          content:
            application/json; charset=utf-8:
              schema:
                $ref: '#definitions/service'
        401:
          description: Bearer token is invalid
          content:
            application/json; charset=utf-8:
              schema:
                $ref: '#definitions/error'
        403:
          description: You do not have proper rights
          content:
            application/json; charset=utf-8:
              schema:
                $ref: '#definitions/error'
        404:
          description: The service was not found by id
          content:
            application/json; charset=utf-8:
              schema:
                $ref: '#definitions/error'
  /services/{id}/subscribe:
    parameters:
      - name: id
        in: path
        schema:
          type: integer
        required: true
        description: The id of the record to query
    post:
      tags:
        - services
      security:
        - bearerAuth: []
      description: Initiate a Stripe session for a payment
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#definitions/service_checkout'
      responses:
        200:
          description: Created a Stripe session OR Subscribed to a free service
          content:
            application/json; charset=utf-8:
              schema:
                type: object
                properties:
                  sessionId:
                    type: integer
        400:
          description: You're already subscribed to the service
          content:
            application/json; charset=utf-8:
              schema:
                $ref: '#definitions/error'
        401:
          description: Bearer token is invalid
          content:
            application/json; charset=utf-8:
              schema:
                $ref: '#definitions/error'
        403:
          description: No tickets available
          content:
            application/json; charset=utf-8:
              schema:
                $ref: '#definitions/error'
