definitions:
  companies:
    type: array
    items:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        email:
          type: string
        picturePath:
          type: string
        latitude:
          type: number
        longitude:
          type: number
        userId:
          type: integer
        stripeId:
          type: string
  company:
    type: object
    properties:
      id:
        type: integer
      name:
        type: string
      email:
        type: string
      picturePath:
        type: string
      latitude:
        type: number
      longitude:
        type: number
      userId:
        type: integer
      stripeId:
        type: string
  company_create:
    type: object
    properties:
      name:
        type: string
        required: true
      email:
        type: string
        required: true
      latitude:
        type: number
        required: true
      longitude:
        type: number
        required: true
  company_update:
    type: object
    properties:
      name:
        type: string
      email:
        type: string
      latitude:
        type: number
      longitude:
        type: number
  company_subscribe:
    type: object
    properties:
      companyId:
        type: integer
  account_completed:
    type: object
    properties:
      isAccountCompleted:
        type: boolean
